# Generated by Django 2.1.4 on 2018-12-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turkey_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=254)),
                ('phone_number', models.IntegerField(default='', max_length=10)),
                ('description', models.TextField()),
                ('turkey', models.CharField(choices=[('whole_turkey', 'WHOLE TURKEY'), ('boned_and_rolled', 'B + R'), ('boneed_rolled_stuffed', 'B + R + S'), ('boned_rolled_own_stuffing', 'B + R + OWN STUFFING'), ('crown', 'CROWN'), ('crown_boned_rolled', 'B + R CROWN'), ('crown_boned_rolled_stuffed', 'B + R + STUFFED'), ('turkey_breast', 'TURKEY BREAST')], default='', max_length=14)),
                ('t_type', models.CharField(choices=[('farm_fresh', 'Aerial'), ('free_range', 'Architecture'), ('organic', 'Landscape')], default='', max_length=14)),
                ('weight', models.CharField(choices=[('2kg', '2KG'), ('2_5kg', '2.5 KG'), ('3kg', '3KG'), ('3_5kg', '3.5KG'), ('4kg', '4kg'), ('4_5kg', '4.5KG'), ('5kg', '5KG'), ('5_5kg', '5.5KG'), ('6_5kg', '6.5KG'), ('7_5kg', '7.5KG'), ('8_5kg', '8.5KG'), ('9_5kg', '9.5KG'), ('10_5kg', '10.5KG')], default='', max_length=14)),
                ('collection_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('staff_initials', models.TextField(choices=[('tom', 'TOM'), ('mick', 'MICK'), ('chris', 'CHRIS')], default='', max_length=10)),
            ],
        ),
    ]
