# Generated by Django 2.1.4 on 2018-12-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkey_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turkey_orders',
            name='t_type',
            field=models.CharField(choices=[('farm_fresh', 'FARM FRESH'), ('free_range', 'FREE RANGE'), ('organic', 'ORGANIC')], default='', max_length=14),
        ),
    ]
