# Generated by Django 2.1.4 on 2018-12-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkey_orders', '0003_remove_turkey_orders_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turkey_orders',
            name='phone_number',
            field=models.IntegerField(default=''),
        ),
    ]
