# Generated by Django 2.1.4 on 2018-12-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkey_orders', '0005_remove_turkey_orders_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turkey_orders',
            name='collection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
