# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkey_orders', '0008_auto_20181225_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='turkey_orders',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
