# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkey_orders', '0010_auto_20181226_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turkey_orders',
            name='phone_number',
            field=models.IntegerField(default=''),
        ),
    ]
