# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-26 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turkey_orders', '0011_auto_20181226_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turkey_orders',
            name='collection_date',
            field=models.CharField(choices=[('21', '21ST'), ('22', '22ND'), ('23', '23RD'), ('24', '24TH'), ('29', '29ND'), ('30', '22ED'), ('31', '22ST')], default='29ND', max_length=20),
        ),
    ]
